### ISSUE TITLE
Make links with tooltip visually different

### ISSUE THREAD

**Issue by humitos** [readthedocs/sphinx-hoverxref#11]
It would be good to make these links visually different from a regular link that won't show a tooltip.

It may be a small icon, or maybe some CSS style.

I was thinking on using the same style as `:abbr:`, that adds a small dotted border at the bottom as the first approach.

![Screenshot_2019-08-19_21-19-30](https://user-images.githubusercontent.com/244656/63292911-10581800-c2c7-11e9-8930-e4e29b4ea2df.png)

**Comment by humitos** [comment]
Small border,

```css
.hoverxref {
  border-bottom: 1px dotted;
}
```

Using an icon,

```css
.hoverxref:after {
  content: " \f05a"";
  font-family: "FontAwesome";
}
```
