### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by flying-sheep** [readthedocs/sphinx-hoverxref#231]
Using this with a theme that has a dark mode makes text in the popup hard to read, see e.g. https://icb-scanpy--2220.com.readthedocs.build/en/2220/api/generated/scanpy.pp.calculate_qc_metrics.html#scanpy.pp.calculate_qc_metrics

![grafik](https://user-images.githubusercontent.com/291575/190378261-9c0b24a4-b667-4577-80d1-0d73e73e83f9.png)

**Comment by humitos** [comment]
Thanks for opening this issue. I'm not a user of dark mode, so I would never have find this issue 😅 

I saw that you are using "furo" theme and I was able to reproduce this issue by going to the link you shared. I don't know too much about CSS, but I'd assume the tooltip should apply the same class that furo is applying for the body when using dark mode. Maybe it's not too complicated to do that and make it match the same style, but 🤷🏼 

I'll see if I come back to this in the following weeks (going on a travel in the next days) and research a little more.

**Comment by flying-sheep** [comment]
Ooo exciting! I hope you have fun on your trip!

Regarding this: Furo sets `<body data-theme="auto">` (or `"dark"` or `"light"`), other themes do it differently. E.g. the [PyData theme](https://pydata-sphinx-theme.readthedocs.io/en/stable/) sets both `data-mode` and `data-theme`. “auto” of course means to derive the mode from the system theme.

I don’t think inheriting from body is too easy
So something like this should work

```css
/* allow users to override these colors without having to replicate a lot of CSS */
:root {
  --hoverxref-bg-color-dark: dimgray;
  --hoverxref-bg-color-light: white;
}

/* defaults derived from system color scheme, set by user except on windows */
@media (prefers-color-scheme: light) {
  body:not([data-theme="dark"]):not([data-mode="dark"]) {
    --hoverxref-bg-color: var(--hoverxref-bg-color-light);
  }
}
@media (prefers-color-scheme: dark) {
  body:not([data-theme="light"]):not([data-mode="light"]) {)
    --hoverxref-bg-color: var(--hoverxref-bg-color-dark);
  }
}

/* explicitly overridden by user */
body:is([data-theme="light"], [data-mode="light"])) {
    --hoverxref-bg-color: var(--hoverxref-bg-color-light);
}
body:is([data-theme="dark"], [data-mode="dark"])) {
    --hoverxref-bg-color: var(--hoverxref-bg-color-dark);
}

/* use variables to set tooltip colors */
.tooltipster-sidetip.tooltipster-shadow .tooltipster-box {
  background-color: var(--hoverxref-bg-color);
}
.tooltipster-sidetip.tooltipster-shadow.tooltipster-right .tooltipster-arrow-border {
  border-right-color: var(--hoverxref-bg-color);
}
/* same for the other directions */
```
